### ISSUE TITLE
vice_libretro.so core not working

### ISSUE THREAD

**Issue by xXS4ALLx** [DrUm78/sdlretro#1]
The **vice_libretro.so** core doesn't seem to be working in this core package, doesn't matter what C64 game I try, either it be Cart, Disk or Tape rom, it just boots back to the game selection screen.

Below is the gmenu2x log file:

**Turning audio amplifier ON
Applied keymap rom command: "keymap rom '/mnt/Roms/Commodore/64/Cart/Activision Decathlon, The (US-EU).crt'"
before setting core vid
In sdl1_video, font regular "/opk/fonts/regular.ttf" not found
In sdl1_video, font bold "/opk/fonts/regular.ttf" not found
after setting core vid
[07-06 01:14:37 I] Unhandled env: 0x1E
In load_variables, l13**

However if I extract the **vice_x64_libretro.so** core file from the the stand alone VICE OPK from **LordEnum** (https://wiki.funkey-project.com/wiki/List_of_third-party_OPK_applications), game loads fine.

**Comment by DrUm78** [comment]
Yes I used to include LordEnum's one as I could not compile it myself. Recently, I managed to compile it so I included mine without testing... I will restore LordEnum's one then, thanks. 👍

**Comment by DrUm78** [comment]
Finally, I chose to remove Vice core as I put only cores that I compile myself and that have the latest source code. LordEnum's unfortunately is based on an old revision. I will add it back if new code works again.
